# By 3A
# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Bellsoft Liberica implementations of JREs and JDKs on musl C library"
  homepage = "https://github.com/bell-sw/buildpacks/liberica"
  id = "bellsoft/buildpacks/liberica"
  keywords = ["java", "jvm", "jre", "jdk"]
  name = "Paketo Buildpack for BellSoft Liberica JDK Lite and Native Image Kit"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "20260225"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/bell-sw/buildpacks/liberica/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/amd64/bin/helper", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "linux/arm64/bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    default = "0"
    description = "the headroom in memory calculation"
    launch = true
    name = "BPL_JVM_HEAD_ROOM"

  [[metadata.configurations]]
    default = "35% of classes"
    description = "the number of loaded classes in memory calculation"
    launch = true
    name = "BPL_JVM_LOADED_CLASS_COUNT"

  [[metadata.configurations]]
    default = "250"
    description = "the number of threads in memory calculation"
    launch = true
    name = "BPL_JVM_THREAD_COUNT"

  [[metadata.configurations]]
    default = ""
    description = "write heap dumps on error to this path"
    launch = true
    name = "BPL_HEAP_DUMP_PATH"

  [[metadata.configurations]]
    default = "true"
    description = "enables Java Native Memory Tracking (NMT)"
    launch = true
    name = "BPL_JAVA_NMT_ENABLED"

  [[metadata.configurations]]
    default = "summary"
    description = "configure level of NMT, summary or detail"
    launch = true
    name = "BPL_JAVA_NMT_LEVEL"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Management Extensions (JMX)"
    launch = true
    name = "BPL_JMX_ENABLED"

  [[metadata.configurations]]
    default = "5000"
    description = "configure the JMX port"
    launch = true
    name = "BPL_JMX_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java remote debugging support"
    launch = true
    name = "BPL_DEBUG_ENABLED"

  [[metadata.configurations]]
    default = "8000"
    description = "configure the remote debugging port"
    launch = true
    name = "BPL_DEBUG_PORT"

  [[metadata.configurations]]
    default = "false"
    description = "configure whether to suspend execution until a debugger has attached"
    launch = true
    name = "BPL_DEBUG_SUSPEND"

  [[metadata.configurations]]
    default = "false"
    description = "enables Java Flight Recording (JFR)"
    launch = true
    name = "BPL_JFR_ENABLED"

  [[metadata.configurations]]
    default = ""
    description = "configure custom Java Flight Recording (JFR) arguments"
    launch = true
    name = "BPL_JFR_ARGS"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "enables running jlink tool to generate custom JRE"
    name = "BP_JVM_JLINK_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "--no-man-pages --no-header-files --strip-debug --compress=1"
    description = "configure custom link arguments (--output must be omitted)"
    name = "BP_JVM_JLINK_ARGS"

  [[metadata.configurations]]
    build = true
    default = "21"
    description = "the Java version"
    name = "BP_JVM_VERSION"

  [[metadata.configurations]]
    build = true
    default = "JRE"
    description = "the JVM type - JDK or JRE"
    name = "BP_JVM_TYPE"

  [[metadata.configurations]]
    description = "the JVM launch flags"
    launch = true
    name = "JAVA_TOOL_OPTIONS"


  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:11.0.30:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "BellSoft Liberica jdk (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jdk@11.0.30?arch=amd64&libc=glibc"
    sha256 = "fb59d528cc089722e4fbc5fb4d304d6069c87f6ab3bed580e3f9b3ae1614df57"
    source = "https://github.com/bell-sw/Liberica/releases/download/11.0.30+9/bellsoft-jdk11.0.30+9-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/11.0.30+9/bellsoft-jdk11.0.30+9-linux-amd64-lite.tar.gz"
    version = "11.0.30"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:17.0.18:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "BellSoft Liberica jdk (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jdk@17.0.18?arch=amd64&libc=glibc"
    sha256 = "b66c3cabff82d6dbe4904ce910612e232be4570120c0aa6315f741af9ec649f3"
    source = "https://github.com/bell-sw/Liberica/releases/download/17.0.18+10/bellsoft-jdk17.0.18+10-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/17.0.18+10/bellsoft-jdk17.0.18+10-linux-amd64-lite.tar.gz"
    version = "17.0.18"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:21.0.10:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "BellSoft Liberica jdk (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jdk@21.0.10?arch=amd64&libc=glibc"
    sha256 = "bfb92dfec976b027d59f80f6555fccbaca59dd5815cde00f195e2078ef09a37c"
    source = "https://github.com/bell-sw/Liberica/releases/download/21.0.10+10/bellsoft-jdk21.0.10+10-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/21.0.10+10/bellsoft-jdk21.0.10+10-linux-amd64-lite.tar.gz"
    version = "21.0.10"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:24.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "BellSoft Liberica jdk (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jdk@24.0.2?arch=amd64&libc=glibc"
    sha256 = "325bc06b98a7da7988953d852c5d1a07d113f985da653ae38e94bb88745c54c2"
    source = "https://github.com/bell-sw/Liberica/releases/download/24.0.2+12/bellsoft-jdk24.0.2+12-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/24.0.2+12/bellsoft-jdk24.0.2+12-linux-amd64-lite.tar.gz"
    version = "24.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jdk:25.0.2:*:*:*:*:*:*:*"]
    id = "jdk"
    name = "BellSoft Liberica jdk (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jdk@25.0.2?arch=amd64&libc=glibc"
    sha256 = "4f740a04dfa604237ce1a52229b0465ce9321fb1dea5e54191c5dfd2ad96c620"
    source = "https://github.com/bell-sw/Liberica/releases/download/25.0.2+12/bellsoft-jdk25.0.2+12-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/25.0.2+12/bellsoft-jdk25.0.2+12-linux-amd64-lite.tar.gz"
    version = "25.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:11.0.30:*:*:*:*:*:*:*"]
    id = "jre"
    name = "BellSoft Liberica jre (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jre@11.0.30?arch=amd64&libc=glibc"
    sha256 = "9cd68530e8b781977a23257fea89e90485c7e915160987c347070fa98945e8ef"
    source = "https://github.com/bell-sw/Liberica/releases/download/11.0.30+9/bellsoft-jdk11.0.30+9-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/11.0.30+9/bellsoft-jre11.0.30+9-linux-amd64-lite.tar.gz"
    version = "11.0.30"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:17.0.18:*:*:*:*:*:*:*"]
    id = "jre"
    name = "BellSoft Liberica jre (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jre@17.0.18?arch=amd64&libc=glibc"
    sha256 = "20635dad825837381e30dba7cc0d6b426030591f3977059b686c2846d1f975d5"
    source = "https://github.com/bell-sw/Liberica/releases/download/17.0.18+10/bellsoft-jdk17.0.18+10-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/17.0.18+10/bellsoft-jre17.0.18+10-linux-amd64-lite.tar.gz"
    version = "17.0.18"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:21.0.10:*:*:*:*:*:*:*"]
    id = "jre"
    name = "BellSoft Liberica jre (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jre@21.0.10?arch=amd64&libc=glibc"
    sha256 = "00c14468545dc241681f099942921547aab0e902929c8ca249000912483b2463"
    source = "https://github.com/bell-sw/Liberica/releases/download/21.0.10+10/bellsoft-jdk21.0.10+10-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/21.0.10+10/bellsoft-jre21.0.10+10-linux-amd64-lite.tar.gz"
    version = "21.0.10"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:24.0.2:*:*:*:*:*:*:*"]
    id = "jre"
    name = "BellSoft Liberica jre (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jre@24.0.2?arch=amd64&libc=glibc"
    sha256 = "4124236cf03f24c240381818e185f6156bf7fc96d194e3097985c51aba476649"
    source = "https://github.com/bell-sw/Liberica/releases/download/24.0.2+12/bellsoft-jdk24.0.2+12-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/24.0.2+12/bellsoft-jre24.0.2+12-linux-amd64-lite.tar.gz"
    version = "24.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:jre:25.0.2:*:*:*:*:*:*:*"]
    id = "jre"
    name = "BellSoft Liberica jre (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-jre@25.0.2?arch=amd64&libc=glibc"
    sha256 = "a82a3b05fdc970e42ff77f4f4af84cdfea9bb44e94abca37627b70f030124f36"
    source = "https://github.com/bell-sw/Liberica/releases/download/25.0.2+12/bellsoft-jdk25.0.2+12-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/25.0.2+12/bellsoft-jre25.0.2+12-linux-amd64-lite.tar.gz"
    version = "25.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:nik:17.0.17:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "BellSoft Liberica native-image-svm (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-nik@23.0.10?arch=amd64&libc=glibc"
    sha256 = "472966d2319457b362701d297d306c7760d830b92e0e381b329325b689167864"
    source = "https://github.com/bell-sw/Liberica/releases/download/17.0.17+12/bellsoft-jdk17.0.17+12-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/17.0.17+12/bellsoft-liberica-vm-core-openjdk17.0.17+12-23.0.10-linux-amd64.tar.gz"
    version = "17.0.17"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:nik:21.0.10:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "BellSoft Liberica native-image-svm (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-nik@23.1.10?arch=amd64&libc=glibc"
    sha256 = "72784fd27f0ed545f079e215d951bb98a79b98b3cccd3b1f05d66eaf63ac5300"
    source = "https://github.com/bell-sw/Liberica/releases/download/21.0.10+11/bellsoft-jdk21.0.10+11-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/21.0.10+11/bellsoft-liberica-vm-core-openjdk21.0.10+11-23.1.10-linux-amd64.tar.gz"
    version = "21.0.10"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:nik:24.0.2:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "BellSoft Liberica native-image-svm (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-nik@24.2.2?arch=amd64&libc=glibc"
    sha256 = "dea4cbf37f3ca0509eca8b5466d7c033bfb566f5207e300a8143875fc6966beb"
    source = "https://github.com/bell-sw/Liberica/releases/download/24.0.2+13/bellsoft-jdk24.0.2+13-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/24.0.2+13/bellsoft-liberica-vm-core-openjdk24.0.2+13-24.2.2-linux-amd64.tar.gz"
    version = "24.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:oracle:nik:25.0.2:*:*:*:*:*:*:*"]
    id = "native-image-svm"
    name = "BellSoft Liberica native-image-svm (Lite or NIK) (glibc)"
    purl = "pkg:generic/bellsoft-nik@25.0.2?arch=amd64&libc=glibc"
    sha256 = "e5456d84de6c95a80d5cc61cf174502a8879f4dc334580c8d4a64615b7c54ad8"
    source = "https://github.com/bell-sw/Liberica/releases/download/25.0.2+13/bellsoft-jdk25.0.2+13-src.tar.gz"
    source-sha256 = "@SRCSHA256@"
    stacks = ["io.buildpacks.stacks.alpaquita-glibc"]
    uri = "https://packages.bell-sw.com/alpaquita/java/25.0.2+13/bellsoft-liberica-vm-core-openjdk25.0.2+13-25.0.2-linux-amd64.tar.gz"
    version = "25.0.2"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0 WITH Classpath-exception-2.0"
      uri = "https://openjdk.java.net/legal/gplv2+ce.html"

[[stacks]]
  id = "io.buildpacks.stacks.alpaquita-musl"

[[stacks]]
  id = "io.buildpacks.stacks.alpaquita-glibc"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
